version: "3.7"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
    restart: always

  reslock:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.prod
    depends_on: 
      - mongodb
    environment:
      - MONGO_DB_NAME=reslock
      - MONGO_SERVER_URL=mongodb:27017/
    ports:
      - 4000:4000
    restart: always

volumes:
  db-data:
  mongo-config: