version: "3.7"

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

    
  reslock:
    build:
      context: ../
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ../:/opt/reslock
    depends_on:
     - mongodb
    environment:
      - MONGO_DB_NAME=reslock
      - MONGO_SERVER_URL=mongodb:27017
    ports:
      - 4000:4000
